// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIfmfOnwCmidAH2OoYaimBkMk8PZwrhP0',
    appId: '1:277532884162:web:f32e6bf8ffc903cb36cf5b',
    messagingSenderId: '277532884162',
    projectId: 'loginapp-ecc8f',
    authDomain: 'loginapp-ecc8f.firebaseapp.com',
    storageBucket: 'loginapp-ecc8f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzv9Ya5YY9OWAeUCOujoU7Q-UrfRX5Oik',
    appId: '1:277532884162:android:90c51ff63509730636cf5b',
    messagingSenderId: '277532884162',
    projectId: 'loginapp-ecc8f',
    storageBucket: 'loginapp-ecc8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX9PsvMoDw9YH5__haS7Z7AeC6Lx_RFvM',
    appId: '1:277532884162:ios:50afdef959c4450736cf5b',
    messagingSenderId: '277532884162',
    projectId: 'loginapp-ecc8f',
    storageBucket: 'loginapp-ecc8f.appspot.com',
    iosBundleId: 'com.example.loginapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX9PsvMoDw9YH5__haS7Z7AeC6Lx_RFvM',
    appId: '1:277532884162:ios:50afdef959c4450736cf5b',
    messagingSenderId: '277532884162',
    projectId: 'loginapp-ecc8f',
    storageBucket: 'loginapp-ecc8f.appspot.com',
    iosBundleId: 'com.example.loginapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIfmfOnwCmidAH2OoYaimBkMk8PZwrhP0',
    appId: '1:277532884162:web:8dcefdaa0f41e9b536cf5b',
    messagingSenderId: '277532884162',
    projectId: 'loginapp-ecc8f',
    authDomain: 'loginapp-ecc8f.firebaseapp.com',
    storageBucket: 'loginapp-ecc8f.appspot.com',
  );

}